/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FarmerRouteImport } from './routes/farmer'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FarmerIndexRouteImport } from './routes/farmer.index'
import { Route as FarmerGrievanceRouteImport } from './routes/farmer.grievance'
import { Route as FarmerApplyRouteImport } from './routes/farmer.apply'

const FarmerRoute = FarmerRouteImport.update({
  id: '/farmer',
  path: '/farmer',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerIndexRoute = FarmerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerGrievanceRoute = FarmerGrievanceRouteImport.update({
  id: '/grievance',
  path: '/grievance',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerApplyRoute = FarmerApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => FarmerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/farmer': typeof FarmerRouteWithChildren
  '/farmer/apply': typeof FarmerApplyRoute
  '/farmer/grievance': typeof FarmerGrievanceRoute
  '/farmer/': typeof FarmerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/farmer/apply': typeof FarmerApplyRoute
  '/farmer/grievance': typeof FarmerGrievanceRoute
  '/farmer': typeof FarmerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/farmer': typeof FarmerRouteWithChildren
  '/farmer/apply': typeof FarmerApplyRoute
  '/farmer/grievance': typeof FarmerGrievanceRoute
  '/farmer/': typeof FarmerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/farmer'
    | '/farmer/apply'
    | '/farmer/grievance'
    | '/farmer/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/farmer/apply' | '/farmer/grievance' | '/farmer'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/farmer'
    | '/farmer/apply'
    | '/farmer/grievance'
    | '/farmer/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  FarmerRoute: typeof FarmerRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/farmer': {
      id: '/farmer'
      path: '/farmer'
      fullPath: '/farmer'
      preLoaderRoute: typeof FarmerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/': {
      id: '/farmer/'
      path: '/'
      fullPath: '/farmer/'
      preLoaderRoute: typeof FarmerIndexRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/grievance': {
      id: '/farmer/grievance'
      path: '/grievance'
      fullPath: '/farmer/grievance'
      preLoaderRoute: typeof FarmerGrievanceRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/apply': {
      id: '/farmer/apply'
      path: '/apply'
      fullPath: '/farmer/apply'
      preLoaderRoute: typeof FarmerApplyRouteImport
      parentRoute: typeof FarmerRoute
    }
  }
}

interface FarmerRouteChildren {
  FarmerApplyRoute: typeof FarmerApplyRoute
  FarmerGrievanceRoute: typeof FarmerGrievanceRoute
  FarmerIndexRoute: typeof FarmerIndexRoute
}

const FarmerRouteChildren: FarmerRouteChildren = {
  FarmerApplyRoute: FarmerApplyRoute,
  FarmerGrievanceRoute: FarmerGrievanceRoute,
  FarmerIndexRoute: FarmerIndexRoute,
}

const FarmerRouteWithChildren =
  FarmerRoute._addFileChildren(FarmerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  FarmerRoute: FarmerRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
