/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as FarmerRouteImport } from './routes/_farmer'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppGrievancesRouteImport } from './routes/_app/grievances'
import { Route as AppFraudRouteImport } from './routes/_app/fraud'
import { Route as AppFieldVerificationRouteImport } from './routes/_app/field-verification'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppApplicationsRouteImport } from './routes/_app/applications'
import { Route as AppAnalyticsRouteImport } from './routes/_app/analytics'
import { Route as FarmerIndexRouteImport } from './routes/_farmer/index'
import { Route as FarmerApplyRouteImport } from './routes/_farmer/apply'
import { Route as FarmerApplicationsRouteImport } from './routes/_farmer/applications'
import { Route as FarmerGrievanceRouteImport } from './routes/_farmer/grievance'

const LoginRoute = LoginRouteImport.update({ id: '/login', path: '/login', getParentRoute: () => rootRouteImport } as any)
const AppRoute = AppRouteImport.update({ id: '/_app', getParentRoute: () => rootRouteImport } as any)
const FarmerRoute = FarmerRouteImport.update({ id: '/_farmer', getParentRoute: () => rootRouteImport } as any)
const IndexRoute = IndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => rootRouteImport } as any)
const AppSettingsRoute = AppSettingsRouteImport.update({ id: '/settings', path: '/settings', getParentRoute: () => AppRoute } as any)
const AppReportsRoute = AppReportsRouteImport.update({ id: '/reports', path: '/reports', getParentRoute: () => AppRoute } as any)
const AppGrievancesRoute = AppGrievancesRouteImport.update({ id: '/grievances', path: '/grievances', getParentRoute: () => AppRoute } as any)
const AppFraudRoute = AppFraudRouteImport.update({ id: '/fraud', path: '/fraud', getParentRoute: () => AppRoute } as any)
const AppFieldVerificationRoute = AppFieldVerificationRouteImport.update({ id: '/field-verification', path: '/field-verification', getParentRoute: () => AppRoute } as any)
const AppDashboardRoute = AppDashboardRouteImport.update({ id: '/dashboard', path: '/dashboard', getParentRoute: () => AppRoute } as any)
const AppApplicationsRoute = AppApplicationsRouteImport.update({ id: '/applications', path: '/applications', getParentRoute: () => AppRoute } as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({ id: '/analytics', path: '/analytics', getParentRoute: () => AppRoute } as any)
const FarmerIndexRoute = FarmerIndexRouteImport.update({ id: '/', path: '/farmer', getParentRoute: () => FarmerRoute } as any)
const FarmerApplyRoute = FarmerApplyRouteImport.update({ id: '/apply', path: '/farmer/apply', getParentRoute: () => FarmerRoute } as any)
const FarmerApplicationsRoute = FarmerApplicationsRouteImport.update({ id: '/applications', path: '/farmer/applications', getParentRoute: () => FarmerRoute } as any)
const FarmerGrievanceRoute = FarmerGrievanceRouteImport.update({ id: '/grievance', path: '/farmer/grievance', getParentRoute: () => FarmerRoute } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/analytics': typeof AppAnalyticsRoute
  '/applications': typeof AppApplicationsRoute
  '/dashboard': typeof AppDashboardRoute
  '/field-verification': typeof AppFieldVerificationRoute
  '/fraud': typeof AppFraudRoute
  '/grievances': typeof AppGrievancesRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/farmer': typeof FarmerIndexRoute
  '/farmer/apply': typeof FarmerApplyRoute
  '/farmer/applications': typeof FarmerApplicationsRoute
  '/farmer/grievance': typeof FarmerGrievanceRoute
}
export interface FileRoutesByTo extends FileRoutesByFullPath {}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_farmer': typeof FarmerRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/applications': typeof AppApplicationsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/field-verification': typeof AppFieldVerificationRoute
  '/_app/fraud': typeof AppFraudRoute
  '/_app/grievances': typeof AppGrievancesRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_farmer/': typeof FarmerIndexRoute
  '/_farmer/apply': typeof FarmerApplyRoute
  '/_farmer/applications': typeof FarmerApplicationsRoute
  '/_farmer/grievance': typeof FarmerGrievanceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/' | '/login' | '/analytics' | '/applications' | '/dashboard'
    | '/field-verification' | '/fraud' | '/grievances' | '/reports' | '/settings'
    | '/farmer' | '/farmer/apply' | '/farmer/applications' | '/farmer/grievance'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/' | '/login' | '/analytics' | '/applications' | '/dashboard'
    | '/field-verification' | '/fraud' | '/grievances' | '/reports' | '/settings'
    | '/farmer' | '/farmer/apply' | '/farmer/applications' | '/farmer/grievance'
  id:
    | '__root__' | '/' | '/_app' | '/_farmer' | '/login'
    | '/_app/analytics' | '/_app/applications' | '/_app/dashboard'
    | '/_app/field-verification' | '/_app/fraud' | '/_app/grievances'
    | '/_app/reports' | '/_app/settings'
    | '/_farmer/' | '/_farmer/apply' | '/_farmer/applications' | '/_farmer/grievance'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  FarmerRoute: typeof FarmerRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': { id: '/login'; path: '/login'; fullPath: '/login'; preLoaderRoute: typeof LoginRouteImport; parentRoute: typeof rootRouteImport }
    '/_app': { id: '/_app'; path: ''; fullPath: '/'; preLoaderRoute: typeof AppRouteImport; parentRoute: typeof rootRouteImport }
    '/_farmer': { id: '/_farmer'; path: ''; fullPath: '/'; preLoaderRoute: typeof FarmerRouteImport; parentRoute: typeof rootRouteImport }
    '/': { id: '/'; path: '/'; fullPath: '/'; preLoaderRoute: typeof IndexRouteImport; parentRoute: typeof rootRouteImport }
    '/_app/settings': { id: '/_app/settings'; path: '/settings'; fullPath: '/settings'; preLoaderRoute: typeof AppSettingsRouteImport; parentRoute: typeof AppRoute }
    '/_app/reports': { id: '/_app/reports'; path: '/reports'; fullPath: '/reports'; preLoaderRoute: typeof AppReportsRouteImport; parentRoute: typeof AppRoute }
    '/_app/grievances': { id: '/_app/grievances'; path: '/grievances'; fullPath: '/grievances'; preLoaderRoute: typeof AppGrievancesRouteImport; parentRoute: typeof AppRoute }
    '/_app/fraud': { id: '/_app/fraud'; path: '/fraud'; fullPath: '/fraud'; preLoaderRoute: typeof AppFraudRouteImport; parentRoute: typeof AppRoute }
    '/_app/field-verification': { id: '/_app/field-verification'; path: '/field-verification'; fullPath: '/field-verification'; preLoaderRoute: typeof AppFieldVerificationRouteImport; parentRoute: typeof AppRoute }
    '/_app/dashboard': { id: '/_app/dashboard'; path: '/dashboard'; fullPath: '/dashboard'; preLoaderRoute: typeof AppDashboardRouteImport; parentRoute: typeof AppRoute }
    '/_app/applications': { id: '/_app/applications'; path: '/applications'; fullPath: '/applications'; preLoaderRoute: typeof AppApplicationsRouteImport; parentRoute: typeof AppRoute }
    '/_app/analytics': { id: '/_app/analytics'; path: '/analytics'; fullPath: '/analytics'; preLoaderRoute: typeof AppAnalyticsRouteImport; parentRoute: typeof AppRoute }
    '/_farmer/': { id: '/_farmer/'; path: '/farmer'; fullPath: '/farmer'; preLoaderRoute: typeof FarmerIndexRouteImport; parentRoute: typeof FarmerRoute }
    '/_farmer/apply': { id: '/_farmer/apply'; path: '/farmer/apply'; fullPath: '/farmer/apply'; preLoaderRoute: typeof FarmerApplyRouteImport; parentRoute: typeof FarmerRoute }
    '/_farmer/applications': { id: '/_farmer/applications'; path: '/farmer/applications'; fullPath: '/farmer/applications'; preLoaderRoute: typeof FarmerApplicationsRouteImport; parentRoute: typeof FarmerRoute }
    '/_farmer/grievance': { id: '/_farmer/grievance'; path: '/farmer/grievance'; fullPath: '/farmer/grievance'; preLoaderRoute: typeof FarmerGrievanceRouteImport; parentRoute: typeof FarmerRoute }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppApplicationsRoute: typeof AppApplicationsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFieldVerificationRoute: typeof AppFieldVerificationRoute
  AppFraudRoute: typeof AppFraudRoute
  AppGrievancesRoute: typeof AppGrievancesRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
}
const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute, AppApplicationsRoute, AppDashboardRoute, AppFieldVerificationRoute,
  AppFraudRoute, AppGrievancesRoute, AppReportsRoute, AppSettingsRoute,
}
const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface FarmerRouteChildren {
  FarmerIndexRoute: typeof FarmerIndexRoute
  FarmerApplyRoute: typeof FarmerApplyRoute
  FarmerApplicationsRoute: typeof FarmerApplicationsRoute
  FarmerGrievanceRoute: typeof FarmerGrievanceRoute
}
const FarmerRouteChildren: FarmerRouteChildren = {
  FarmerIndexRoute, FarmerApplyRoute, FarmerApplicationsRoute, FarmerGrievanceRoute,
}
const FarmerRouteWithChildren = FarmerRoute._addFileChildren(FarmerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute, AppRoute: AppRouteWithChildren, FarmerRoute: FarmerRouteWithChildren, LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
