/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppGrievancesRouteImport } from './routes/_app/grievances'
import { Route as AppFraudRouteImport } from './routes/_app/fraud'
import { Route as AppFieldVerificationRouteImport } from './routes/_app/field-verification'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppApplicationsRouteImport } from './routes/_app/applications'
import { Route as AppAnalyticsRouteImport } from './routes/_app/analytics'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppGrievancesRoute = AppGrievancesRouteImport.update({
  id: '/grievances',
  path: '/grievances',
  getParentRoute: () => AppRoute,
} as any)
const AppFraudRoute = AppFraudRouteImport.update({
  id: '/fraud',
  path: '/fraud',
  getParentRoute: () => AppRoute,
} as any)
const AppFieldVerificationRoute = AppFieldVerificationRouteImport.update({
  id: '/field-verification',
  path: '/field-verification',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppApplicationsRoute = AppApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/analytics': typeof AppAnalyticsRoute
  '/applications': typeof AppApplicationsRoute
  '/dashboard': typeof AppDashboardRoute
  '/field-verification': typeof AppFieldVerificationRoute
  '/fraud': typeof AppFraudRoute
  '/grievances': typeof AppGrievancesRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/analytics': typeof AppAnalyticsRoute
  '/applications': typeof AppApplicationsRoute
  '/dashboard': typeof AppDashboardRoute
  '/field-verification': typeof AppFieldVerificationRoute
  '/fraud': typeof AppFraudRoute
  '/grievances': typeof AppGrievancesRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/applications': typeof AppApplicationsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/field-verification': typeof AppFieldVerificationRoute
  '/_app/fraud': typeof AppFraudRoute
  '/_app/grievances': typeof AppGrievancesRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/settings': typeof AppSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/analytics'
    | '/applications'
    | '/dashboard'
    | '/field-verification'
    | '/fraud'
    | '/grievances'
    | '/reports'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/analytics'
    | '/applications'
    | '/dashboard'
    | '/field-verification'
    | '/fraud'
    | '/grievances'
    | '/reports'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/analytics'
    | '/_app/applications'
    | '/_app/dashboard'
    | '/_app/field-verification'
    | '/_app/fraud'
    | '/_app/grievances'
    | '/_app/reports'
    | '/_app/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/grievances': {
      id: '/_app/grievances'
      path: '/grievances'
      fullPath: '/grievances'
      preLoaderRoute: typeof AppGrievancesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fraud': {
      id: '/_app/fraud'
      path: '/fraud'
      fullPath: '/fraud'
      preLoaderRoute: typeof AppFraudRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/field-verification': {
      id: '/_app/field-verification'
      path: '/field-verification'
      fullPath: '/field-verification'
      preLoaderRoute: typeof AppFieldVerificationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/applications': {
      id: '/_app/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof AppApplicationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppApplicationsRoute: typeof AppApplicationsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFieldVerificationRoute: typeof AppFieldVerificationRoute
  AppFraudRoute: typeof AppFraudRoute
  AppGrievancesRoute: typeof AppGrievancesRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppApplicationsRoute: AppApplicationsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFieldVerificationRoute: AppFieldVerificationRoute,
  AppFraudRoute: AppFraudRoute,
  AppGrievancesRoute: AppGrievancesRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
